#!/usr/bin/python3

"""
checks the number of characters in a given file.

-l, --literal: number of characters in the actual input string
  cc -l hi
  >>> 2 // 'hi' is 2 characters
otherwise try to open a file
  cc "main.py"
  >>> 300 // main.py has 300 characters in it 
"""

import string 
import argparse

def countFile(file:str, ignore_whitespace=False): # returns the # of characters in a file 
    try:
        with open(file, "r") as f:
            contents = f.read()

        i:int =0
        for char in contents:
            if ignore_whitespace:
                if char not in string.whitespace:
                    i+=1
            else:
                i+=1

        return i
    except Exception as e:
        return f"Cannot read file: {file} \n{e}"



if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='return the number of characters in a file')
    parser.add_argument('file',
                        help='the file used')
    parser.add_argument('--ignore-whitespace', '-i',
                        action='store_true',
                        default=False,
                        help='ignore whitespace')

    args = parser.parse_args()

    print(countFile(args.file, args.ignore_whitespace))
