#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
getdolphin() {
	echo 'Downloading Dolphin...'
	git clone https://github.com/dolphin-emu/dolphin.git
}
updatedolphin() {
	cd $DIR/dolphin
	echo 'Updating the local repository...'
	git pull origin
}
build() {
	cmake $DIR/dolphin
	make
}
updatedolphin || getdolphin
mkdir $DIR/build
cd $DIR/build
build && echo 'Compiled successfully.' || exit
echo 'Proceeding to the installation; press Enter to continue or Ctrl+C to cancel.'
read
if [ $(whoami) == "root" ];
	then
		make install
	else
		sudo make install
fi
