#!/bin/bash
# this updates discord from the cli
# Just makes it faster than clicking the url and running the dpkg -i command myself

rm download\?platform\=linux # removes the file beforehand
wget https://discord.com/api/download?platform=linux&format=deb # downloads discord
echo -e "\033[31;1mThe following runs dpkg -i to install the discord .deb package. it requires sudo. Check the source code in ~/programming/scripts/update_discord if you dont believe me.\033[0m"
sudo dpkg -i download\?platform\=linux # installs discord
rm download\?platform\=linux # removes the file
